# --- CẤU HÌNH EUREKA ---
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# --- ROUTE 0: PRODUCT SERVICE ---
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
# Nhận diện link bắt đầu bằng /api/v1/products
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/products/**
# Cắt bỏ 3 phần đầu (/api, /v1, /products) trước khi gửi đến Service 
# để Service nhận được request sạch (ví dụ: /all thay vì /api/v1/products/all)
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=3

# --- ROUTE 1: INVENTORY SERVICE ---
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/inventory/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=3

# --- ROUTE 2: USER SERVICE ---
spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=lb://user-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=3
