spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
management.endpoints.web.exposure.include=*
management.endpoint.bus-refresh.enabled=true 
management.endpoint.bus-env.enabled=true
spring.cloud.bus.enabled=true
spring.cloud.bus.destination=springCloudBus

app.security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

app.security.jwt.expiration=3600
app.jwt.refresh-token-validity-in-seconds=2592000

app.security.public-urls=/api/v1/auth/**,/api/v1/products/**,/eureka/**,/actuator/**,/h2-console/**

spring.cloud.config.override-none=true
